"""Add duration to message

Revision ID: 0a0f44c3a6a3
Revises: a888790fc3a7
Create Date: 2026-04-29 18:14:08.151324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0f44c3a6a3'
down_revision: Union[str, Sequence[str], None] = 'a888790fc3a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('duration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'duration')
    # ### end Alembic commands ###
